services:
  Nginx:
    platform: linux/amd64
    build: 
      context: "./Nginx/."
    image : movingju/public:nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - DRIVE_NET
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - blog
    restart: unless-stopped
  blog:
    platform: linux/amd64
    build: 
      context: "./blog/."
    image: movingju/public:blog
    ports:
      - "4000:4000"
    networks:
      - DRIVE_NET

networks:
  DRIVE_NET:
    driver: bridge