name: Docker Image CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: aws
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.AWS_EC2_KEY }}

      - name: Run CI/CD.sh on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} "
            cd /home/${{ secrets.AWS_EC2_USER }}/movingju.com/ 
            git fetch --all
            git reset --hard origin/main
            cd blog
            docker build -t movingju/public:blog .
            docker run -p 4000:4000 -d movingju/public:blog
          "